server:
  port: 8090

spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    mcp:
      client:
        request-timeout: 360s
        stdio:
          servers-configuration: classpath:/config/mcp-servers-config.json
    google:
      genai:
        # Google GenAI SDK 模式的代理服务
        base-url: http://127.0.0.1:8045
        api-key: sk-1256419209eb47ccbabaa98abccfe4c8
        chat:
          options:
            model: gemini-3-flash
    openai:
      base-url: http://127.0.0.1:8045
      api-key: sk-1256419209eb47ccbabaa98abccfe4c8
      chat:
        options:
          model: gemini-3-flash
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://1b349d2280564f15a7ef-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

# 向量存储表名配置
vector:
  store:
    openai:
      table-name: vector_store_openai
    ollama:
      table-name: vector_store_ollama_deepseek

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
