spring:
  application:
    # 应用名称（日志/注册中心等会使用）
    name: ai-rag-knowledge
  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
  profiles:
    # 默认激活的运行环境
    active: dev

mybatis-plus:
  # Mapper XML 路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 自动将下划线字段映射为驼峰属性
    map-underscore-to-camel-case: true

logging:
  # 默认日志输出目录
  path: /Users/sxie/xbk/ai-mcp-knowledge-study/logs/app

chat:
  history:
    # 聊天记录保留天数
    retention-days: 7
    # 上下文窗口大小
    memory-window-size: 20

mcp:
  tools:
    # 工具清单缓存秒数
    cache-seconds: 60

xxl:
  job:
    # XXL-Job 执行器配置
    executor:
      # 执行器 AppName（与调度中心配置的执行器名称一致）
      appname: ai-rag-knowledge-executor
      # 执行器注册地址（调度中心地址）
      admin-addresses: http://127.0.0.1:9090/xxl-job-admin
      # 执行器端口（默认9999，多个执行器注意端口冲突）
      port: 9999
      # 执行器日志路径
      logpath: /Users/sxie/xbk/ai-mcp-knowledge-study/logs/xxl-job
      # 执行器日志保留天数
      logretentiondays: 30
    # 执行器通讯TOKEN（与调度中心配置一致）
    accessToken: default_token
  admin:
    # 调度中心地址
    base-url: http://127.0.0.1:9090/xxl-job-admin
    # 登录账号
    username: admin
    # 登录密码
    password: 123456
    # 执行器 AppName
    app-name: ai-rag-knowledge-executor
    # Cookie 缓存秒数
    cookie-ttl-seconds: 1800
    # 任务下拉缓存秒数
    job-cache-ttl-seconds: 600

sa-token:
  # token 名称（前端请求头中使用）
  token-name: satoken
  # 允许在 header 中读取 token
  is-read-header: true
  # 禁止从 cookie 读取 token，减少跨域干扰
  is-read-cookie: false
